import { flag, flat, inc, more } from '../../core/mods';
import { Registry } from '../../core/registry';
import type { MonsterArchetypeDef } from '../types';

/**
 * Behaviour archetypes as data. `skills` lists roles or skill ids: 'melee' resolves per
 * body (bite / claw / weapon swing), 'bolt' per theme (fire / frost / spark / void). The
 * brain (brains/brain.ts) reads `brain`; the generator reads `planWeights`, `scale` and
 * `prefers` (part tags it favours).
 */
const A = (a: Omit<MonsterArchetypeDef, 'plans' | 'tags'> & { tags?: readonly string[] }): MonsterArchetypeDef => ({
  ...a,
  tags: a.tags ?? [],
  plans: Object.keys(a.planWeights),
});

export const ARCHETYPES = new Registry<MonsterArchetypeDef>('archetypes', [
  A({
    id: 'charger',
    name: 'Charger',
    description: 'Lowers its head and charges across the room; gores on contact.',
    planWeights: { quadruped: 3, brute: 2, biped: 0.6, centipede: 1, hexapod: 0.8 },
    skills: ['charge', 'melee'],
    mods: [flat('knockback', 2), inc('life', 0.15)],
    brain: { aggro: 13, leash: 26, range: [0, 1.1], strafe: 0.1, retreat: 0, flee: 0, speed: 1.1, think: 0.25 },
    pack: [2, 4],
    scale: 1.05,
    prefers: ['horns', 'beast', 'earth'],
  }),
  A({
    id: 'skirmisher',
    name: 'Skirmisher',
    description: 'Darts in, bites, darts out; circles you between strikes.',
    planWeights: { quadruped: 2, hexapod: 2, biped: 1.5, avian: 2, serpent: 1, centipede: 1 },
    skills: ['melee'],
    mods: [inc('move.speed', 0.25), inc('attack.speed', 0.1), more('life', -0.15)],
    brain: { aggro: 12, leash: 24, range: [0, 1.0], strafe: 0.65, retreat: 1.1, flee: 0, speed: 1.25, think: 0.2 },
    pack: [3, 5],
    scale: 0.9,
    prefers: ['beast', 'insect'],
  }),
  A({
    id: 'caster',
    name: 'Caster',
    description: 'Keeps its distance and throws elemental bolts; novas if you close in.',
    planWeights: { biped: 3, floater: 3, serpent: 1, avian: 0.5 },
    skills: ['bolt', 'nova'],
    mods: [inc('damage', 0.15, ['spell']), more('life', -0.2)],
    brain: { aggro: 14, leash: 24, range: [5, 8.5], strafe: 0.45, retreat: 0, flee: 0, speed: 0.9, think: 0.3 },
    pack: [1, 3],
    scale: 0.95,
    prefers: ['arcane', 'crystal', 'staff', 'core'],
  }),
  A({
    id: 'summoner',
    name: 'Summoner',
    description: 'Hangs back behind a wall of minions it keeps calling.',
    planWeights: { biped: 2, floater: 2, blob: 1, brute: 0.5 },
    skills: ['summon', 'bolt'],
    mods: [inc('cast.speed', 0.15), more('life', -0.1)],
    brain: { aggro: 15, leash: 24, range: [7, 11], strafe: 0.3, retreat: 0, flee: 0.35, speed: 0.85, think: 0.35 },
    pack: [1, 2],
    scale: 1,
    prefers: ['undead', 'void', 'arcane', 'helm'],
  }),
  A({
    id: 'bomber',
    name: 'Bomber',
    description: 'Rushes you, swells and bursts; kill it at range.',
    planWeights: { blob: 3, floater: 2, hexapod: 1, centipede: 0.6 },
    skills: ['explode'],
    mods: [inc('move.speed', 0.3), more('life', -0.4)],
    brain: { aggro: 11, leash: 22, range: [0, 1.2], strafe: 0, retreat: 0, flee: 0, speed: 1.35, think: 0.2 },
    pack: [2, 4],
    scale: 0.8,
    prefers: ['fire', 'core', 'poison'],
  }),
  A({
    id: 'tank',
    name: 'Tank',
    description: 'Slow, armoured, blocks hits from the front; slams the ground.',
    planWeights: { brute: 3, quadruped: 1, biped: 1, centipede: 0.5 },
    skills: ['slam', 'melee'],
    mods: [more('life', 0.5), flat('armour', 60), flag('frontalBlock'), inc('move.speed', -0.2), flat('stun.threshold', 0.5)],
    brain: { aggro: 10, leash: 20, range: [0, 1.3], strafe: 0, retreat: 0, flee: 0, speed: 0.75, think: 0.4 },
    pack: [1, 2],
    scale: 1.3,
    prefers: ['armour', 'shell', 'plates', 'helm', 'construct'],
  }),
  A({
    id: 'swarm',
    name: 'Swarm',
    description: 'Weak alone, many together: floods around you.',
    planWeights: { hexapod: 3, avian: 2, blob: 1.5, centipede: 1, serpent: 1, quadruped: 1 },
    skills: ['melee'],
    mods: [more('life', -0.6), more('damage', -0.4), inc('move.speed', 0.15)],
    brain: { aggro: 12, leash: 22, range: [0, 0.9], strafe: 0.3, retreat: 0, flee: 0, speed: 1.2, think: 0.3 },
    pack: [5, 9],
    scale: 0.55,
    prefers: ['insect', 'beast'],
  }),
  A({
    id: 'sniper',
    name: 'Sniper',
    description: 'Long aimed shots from afar; a line telegraphs each one.',
    planWeights: { biped: 2, floater: 2, hexapod: 1, serpent: 1, avian: 0.5 },
    skills: ['snipe', 'spit'],
    mods: [inc('crit.chance', 0.5), more('life', -0.25), inc('projectile.speed', 0.2)],
    brain: { aggro: 16, leash: 26, range: [9, 13], strafe: 0.3, retreat: 0, flee: 0.2, speed: 0.95, think: 0.35 },
    pack: [1, 2],
    scale: 0.95,
    prefers: ['eyes', 'stalk', 'spear'],
  }),
  A({
    id: 'leaper',
    name: 'Leaper',
    description: 'Pounces from range onto a marked spot, then mauls.',
    planWeights: { quadruped: 2, hexapod: 2, avian: 1.5, blob: 1, biped: 1 },
    skills: ['leap', 'melee'],
    mods: [inc('move.speed', 0.1), inc('damage', 0.1)],
    brain: { aggro: 12, leash: 24, range: [0, 1.1], strafe: 0.35, retreat: 0.6, flee: 0, speed: 1.1, think: 0.25 },
    pack: [2, 4],
    scale: 0.95,
    prefers: ['beast', 'claws', 'talons'],
  }),
  A({
    id: 'totem',
    name: 'Totem',
    description: 'Rooted turret: shoots bolts and pulses a ward that empowers nearby monsters.',
    planWeights: { floater: 2, blob: 2, serpent: 0.6 },
    skills: ['bolt', 'ward'],
    mods: [more('life', 0.4), flat('armour', 30), flag('rooted'), flag('knockbackImmune')],
    brain: { aggro: 13, leash: 0, range: [0, 12], strafe: 0, retreat: 0, flee: 0, speed: 0, rooted: true, think: 0.4 },
    pack: [1, 1],
    scale: 1.1,
    prefers: ['crystal', 'core', 'construct', 'arcane'],
  }),
]);
