/**
 * The field guide: every word the station guides use, in plain language. Rooms list the
 * words they use (`guide.words`); `glossary.test.ts` checks every one is defined here.
 */
export interface Term {
  readonly term: string;
  readonly section: 'pixels' | 'rendering' | 'motion' | 'physics' | 'animation' | 'effects' | 'games' | 'tools';
  readonly text: string;
}

export const SECTIONS: Readonly<Record<Term['section'], string>> = {
  pixels: 'Pixels and screens',
  rendering: 'Rendering',
  effects: 'Effects',
  motion: 'Movement and feel',
  physics: 'Physics',
  animation: 'Animation',
  games: 'Game systems',
  tools: 'Tools',
};

export const GLOSSARY: readonly Term[] = [
  // pixels
  { term: 'art resolution', section: 'pixels', text: 'The size the picture is really drawn at (480 x 270 by default): one fragment per art pixel. The canvas is a whole multiple of it.' },
  { term: 'art pixel', section: 'pixels', text: 'One pixel of the art resolution. On a 1920 x 1080 screen at 4x it is a 4 x 4 block of screen pixels.' },
  { term: 'integer scaling', section: 'pixels', text: 'Upscaling by a whole number (2x, 3x, 4x) so every art pixel becomes the same square block: no blur, no uneven pixels.' },
  { term: 'nearest-neighbour', section: 'pixels', text: 'Sampling that takes the closest texel instead of blending neighbours: crisp pixel edges.' },
  { term: 'palette', section: 'pixels', text: 'A small fixed set of colours (this engine uses Sweetie 16). Filters can snap the picture to another one: NES, Game Boy, CGA...' },
  { term: 'dither', section: 'pixels', text: 'A pattern of two colours that the eye mixes into an in-between shade. Ordered dither uses a fixed 4 x 4 Bayer matrix.' },
  { term: 'Bayer matrix', section: 'pixels', text: 'A 4 x 4 table of thresholds 0..15/16 laid out so neighbouring pixels differ a lot: the classic ordered-dither pattern.' },
  { term: 'letterbox', section: 'pixels', text: 'Bars around the picture when the screen is not a whole multiple of the art size.' },
  // rendering
  { term: 'TSL', section: 'rendering', text: 'Three Shading Language: shaders written as JavaScript node graphs, compiled to WGSL for WebGPU or GLSL for the WebGL 2 fallback.' },
  { term: 'uniform', section: 'rendering', text: 'A value a shader reads that the CPU can change every frame without rebuilding the shader: slider moves, transitions, light colours.' },
  { term: 'render pipeline', section: 'rendering', text: 'The chain of passes that makes a frame: the scene pass, outlines, filters, the upscale.' },
  { term: 'toon shading', section: 'rendering', text: 'Lighting quantised into a few hard bands (3 here) instead of a smooth gradient: the hand-shaded sprite look.' },
  { term: 'outline', section: 'rendering', text: 'Dark pixels where depth jumps (a silhouette edge), found by comparing each art pixel with its neighbours.' },
  { term: 'crease', section: 'rendering', text: 'A light line where the surface normal turns sharply (inner edges of a box).' },
  { term: 'filter', section: 'rendering', text: 'A post-process step on the finished picture: a palette, a colour grade, scanlines, a CRT.' },
  { term: 'look', section: 'rendering', text: 'A whole recipe: pixel art or clean, and a filter stack, for the characters, the environment and the whole frame.' },
  { term: 'look layer', section: 'rendering', text: 'Characters and objects are one layer, the environment the other; each can have its own pixel size and filters.' },
  { term: 'draw call', section: 'rendering', text: 'One request to the GPU to draw a mesh with a material. Fewer is faster; merging static meshes cuts hundreds to dozens.' },
  { term: 'shadow map', section: 'rendering', text: 'A depth picture taken from the sun: a pixel is in shadow when something is closer to the sun than it is.' },
  { term: 'texel snapping', section: 'rendering', text: 'Moving the shadow camera only by whole shadow-map texels so shadow edges do not crawl while the view follows the player.' },
  { term: 'point light', section: 'rendering', text: 'A light at a point that fades with distance: torches, lamps, spells.' },
  { term: 'light pool', section: 'rendering', text: 'A fixed number of real lights handed each frame to the most important light requests, so adding torches never recompiles shaders.' },
  { term: 'hysteresis', section: 'rendering', text: 'Favouring the current owner a little so two equal candidates do not swap back and forth every frame.' },
  { term: 'orthographic', section: 'rendering', text: 'A projection with no perspective: far things are as big as near ones. Isometric, top-down and side views use it.' },
  { term: 'perspective', section: 'rendering', text: 'A projection where far things look smaller: third and first person.' },
  { term: 'WebGPU', section: 'rendering', text: 'The modern browser graphics API this engine targets first; WebGL 2 is the fallback with the same scene and shaders.' },
  // effects
  { term: 'particle', section: 'effects', text: 'A tiny sprite with a position, speed and life. Thousands of them draw as one instanced draw call.' },
  { term: 'instancing', section: 'effects', text: 'Drawing many copies of one mesh in a single draw call, each with its own position (and colour).' },
  { term: 'flicker', section: 'effects', text: 'A light whose brightness wobbles in a pattern: torch, candle, brazier, pulse, strobe.' },
  { term: 'screen transition', section: 'effects', text: 'Covering and uncovering the picture between scenes: fades, an iris, diamonds, blinds, a mosaic.' },
  { term: 'iris', section: 'effects', text: 'A circle that closes on a point (usually the player) to black, then opens again.' },
  { term: 'shockwave', section: 'effects', text: 'A ring that pushes the picture outwards from a blast: the screen is resampled with offset coordinates near the ring.' },
  { term: 'flash', section: 'effects', text: 'The whole screen washed with a colour for a moment: a hit, a lightning strike, a camera flash.' },
  { term: 'mosaic', section: 'effects', text: 'Pixel blocks that grow until the picture is a few squares: the SNES-era scene change.' },
  // motion
  { term: 'fixed timestep', section: 'motion', text: 'Physics always advances 1/60 s at a time, however fast the screen draws, so movement is the same on every machine.' },
  { term: 'interpolation', section: 'motion', text: 'Drawing objects between their last two physics positions so motion is smooth when frames and steps do not line up.' },
  { term: 'time scale', section: 'motion', text: 'A multiplier on game time: 0.25 is slow motion, 2 is double speed. Physics, animation and particles all follow it.' },
  { term: 'hitstop', section: 'motion', text: 'Freezing the game for a few frames when a hit lands so it feels heavy (also called hit pause or hit lag).' },
  { term: 'screen shake', section: 'motion', text: 'Jolting the camera on impacts. Driven by trauma, which decays; the offset grows with trauma squared.' },
  { term: 'trauma', section: 'motion', text: 'A 0..1 amount that hits add to and time drains; shake strength is trauma squared, so small hits barely shake.' },
  { term: 'tween', section: 'motion', text: 'Moving a value from A to B over time with an easing curve: doors, lifts, menus, pickups.' },
  { term: 'easing', section: 'motion', text: 'The shape of a tween: ease out starts fast and settles, back overshoots, bounce bounces, steps holds poses.' },
  { term: 'camera preset', section: 'motion', text: 'A whole camera setup: isometric, top-down, side, third person, first person, free, fixed.' },
  { term: 'pixel snapping', section: 'motion', text: 'Moving an orthographic camera only by whole art pixels so the picture never swims; physics is never snapped.' },
  { term: 'coyote time', section: 'motion', text: 'A short moment after running off a ledge when a jump still works.' },
  { term: 'jump buffer', section: 'motion', text: 'Remembering a jump pressed just before landing and doing it on touchdown.' },
  // physics
  { term: 'rigid body', section: 'physics', text: 'A solid object the physics engine moves: dynamic (forces move it), kinematic (code moves it) or fixed.' },
  { term: 'collider', section: 'physics', text: 'The shape physics uses for a body: a box, sphere, capsule, cylinder.' },
  { term: 'trigger', section: 'physics', text: 'A volume that reports what enters and leaves it but never blocks anything: pickups, doors, pads.' },
  { term: 'raycast', section: 'physics', text: 'Shooting a line and asking what it hits first: ground checks, line of sight, camera walls.' },
  { term: 'character controller', section: 'physics', text: 'Code that moves a capsule by sweeping it through the world and sliding along walls, with stairs and slopes.' },
  { term: 'Rapier', section: 'physics', text: 'The physics engine underneath (Rust compiled to WebAssembly).' },
  { term: 'dynamic body', section: 'physics', text: 'A rigid body that forces, gravity and collisions move. It has a mass (density times volume).' },
  { term: 'kinematic body', section: 'physics', text: 'A rigid body code moves (a lift, a door): it pushes dynamic bodies but nothing pushes it back.' },
  { term: 'impulse', section: 'physics', text: 'An instant change of momentum (a kick, a blast): velocity changes by impulse / mass at once.' },
  { term: 'friction', section: 'physics', text: 'How much two touching surfaces resist sliding. Ice is near 0, rubber near 1 or more.' },
  { term: 'restitution', section: 'physics', text: 'Bounciness: the share of speed kept after a hit. 0 thuds, 1 bounces forever.' },
  { term: 'density', section: 'physics', text: 'Mass per volume. A dense box is heavy: harder to push, it pushes light boxes away.' },
  { term: 'sleeping', section: 'physics', text: 'A body that has been still for a moment stops being simulated until something touches it: big piles cost almost nothing at rest.' },
  { term: 'solver', section: 'physics', text: 'The part of the physics engine that pushes overlapping bodies apart and keeps joints together, a few passes per step. More passes: stiffer stacks.' },
  { term: 'CCD', section: 'physics', text: 'Continuous collision detection: fast, small bodies are swept along their path so they cannot skip through thin walls between two steps.' },
  { term: 'joint', section: 'physics', text: 'A rule that ties two bodies together: a ball joint (free turning about a point), a hinge (one axis), a slider (one direction), fixed, rope or spring.' },
  { term: 'collision groups', section: 'physics', text: 'Bit masks saying which colliders can touch which: a ragdoll\'s limbs hit the world but not each other.' },
  { term: 'ball joint', section: 'physics', text: 'A joint that keeps two points together but lets the bodies turn any way: chains, punching bags, ragdoll shoulders.' },
  { term: 'hinge', section: 'physics', text: 'A revolute joint: two bodies turn about one shared axis, often with limits (a door opens 110 degrees) and a motor.' },
  { term: 'slider', section: 'physics', text: 'A prismatic joint: a body moves along one axis only, with limits, and a motor can act as a spring (pistons, spring pads).' },
  { term: 'motor', section: 'physics', text: 'A joint drive that pushes toward a target angle, position or speed with a stiffness and damping: a door that swings shut, a spinning wheel.' },
  { term: 'Verlet integration', section: 'physics', text: 'Moving a particle by how far it moved last step (position - previous position) plus acceleration: velocity is implicit, so constraints just move positions.' },
  { term: 'constraint', section: 'physics', text: 'A rule a solver keeps true: two particles stay 0.2 m apart, a pinned particle stays put, a blob keeps its volume.' },
  { term: 'soft body', section: 'physics', text: 'Something that bends and squishes instead of staying rigid: cloth, ropes, jelly. Here: particles held together by distance constraints.' },
  { term: 'cloth', section: 'physics', text: 'A grid of particles with constraints along its threads (structure), across its squares (shear) and two apart (bending).' },
  { term: 'pressure', section: 'physics', text: 'A soft blob pushes its surface out toward its starting volume, so it bulges back after a squash instead of collapsing.' },
  { term: 'mover', section: 'physics', text: 'A kinematic body moved along a path, spun or swung as a pure function of physics time: platforms, lifts, turntables.' },
  { term: 'conveyor', section: 'physics', text: 'A surface that carries what touches it at its own speed without moving itself: belts, treadmills, river rafts.' },
  { term: 'force field', section: 'physics', text: 'A volume that pushes whatever is inside: wind (a direction), a fan (an updraft), a magnet or a black hole (toward or away from a point), drag (water).' },
  { term: 'drag', section: 'physics', text: 'A force against the velocity relative to the medium: it slows things in water and makes them drift with a current.' },
  { term: 'fracture', section: 'physics', text: 'Cutting a block into pieces before it breaks (here: jittered planes, so the pieces tile the block exactly), then swapping the block for the pieces.' },
  { term: 'debris', section: 'physics', text: 'The pieces left after something breaks: real bodies for a few seconds, then they fade away so the world does not fill up.' },
  { term: 'dissolve', section: 'rendering', text: 'Fading a mesh out by discarding more and more of its pixels in a fixed pattern: no transparency sorting, still crisp pixel art.' },
  { term: 'buoyancy', section: 'physics', text: 'Water pushing up on what is in it with the weight of the water it displaces: lighter than water floats, heavier sinks.' },
  { term: 'ripples', section: 'effects', text: 'Rings that spread on water from a disturbance: here the 2D wave equation on a grid, each cell pulled toward the average of its neighbours.' },
  { term: 'day cycle', section: 'effects', text: 'Time of day as keyframes: the sun\'s direction, colour and strength, the ambient light and the sky, blended hour by hour.' },
  { term: 'fog', section: 'rendering', text: 'Blending distant or low parts of the picture toward a colour: depth, mood, and hiding where the world ends.' },
  { term: 'decal', section: 'rendering', text: 'A mark laid on a surface (a footprint, a scorch mark, paint): a small flat shape along the surface, nudged off it so it never flickers into it.' },
  { term: 'trail', section: 'effects', text: 'A ribbon through the last points something passed, facing the camera and thinning toward its tail: sword swings, dashes, comets.' },
  { term: 'wind sway', section: 'effects', text: 'Leaning the vertices of plants and trees along the wind in the vertex shader, more the higher they are: the trunk stays, the crown moves.' },
  // animation
  { term: 'clip', section: 'animation', text: 'One animation (Run, Jump, Wave): key poses over time, written here as data.' },
  { term: 'cross-fade', section: 'animation', text: 'Blending from one clip to the next over a moment instead of snapping.' },
  { term: 'ragdoll', section: 'animation', text: 'A character whose joints are handed to physics: each limb a body, held to the next by a joint with limits, so it falls and tumbles like a rag doll.' },
  { term: 'animation blending', section: 'animation', text: 'Mixing two poses joint by joint (each rotation part of the way from one to the other): how a ragdoll eases back into a get-up clip.' },
  { term: 'blend space', section: 'animation', text: 'Several clips mixed by a parameter: tiptoe, walk and run blended by speed.' },
  { term: 'foot IK', section: 'animation', text: 'Inverse kinematics that bends the legs so the feet land on the real ground: stairs, slopes, ledges.' },
  { term: 'contact sheet', section: 'animation', text: 'A grid of frames of a clip in one picture, to check it by eye.' },
  { term: 'rig', section: 'animation', text: 'The joints of a character and how they are named and limited.' },
  { term: 'secondary motion', section: 'animation', text: 'Motion that follows other motion (a scarf trailing, a tail swinging past when you stop): here springs on bones, worked out every frame.' },
  { term: 'squash and stretch', section: 'animation', text: 'Squashing a shape on impact and stretching it in fast motion while keeping its volume: the oldest trick for weight and life.' },
  { term: 'procedural animation', section: 'animation', text: 'Motion computed every frame from rules (where feet should be, how a spring swings) instead of played from keyframes.' },
  { term: 'IK', section: 'animation', text: 'Inverse kinematics: working out the joints from where the end should be (the foot on the step, the hand on the ledge). Two bones solve exactly with the law of cosines.' },
  { term: 'gait', section: 'animation', text: 'The pattern in which legs take turns: a trot, an insect\'s tripod. Here it emerges from "a leg waits while its neighbours step".' },
  { term: 'sprite', section: 'pixels', text: 'A small 2D picture (often one frame of a sheet) drawn as it is: characters, items, effects. Frames flip to animate.' },
  { term: 'billboard', section: 'rendering', text: 'A flat picture that always turns to face the camera: pixel sprites in a 3D world, like Doom\'s monsters or Paper Mario.' },
  // games
  { term: 'pad', section: 'games', text: 'A plate on the floor in these rooms: step on it to change a setting.' },
  { term: 'game loop', section: 'games', text: 'Every frame: read input, step physics (fixed steps), update the game, update the camera, draw.' },
  { term: 'navigation grid', section: 'games', text: 'The level as a grid of cells marked walkable or blocked: what paths, flow fields and line-of-sight checks run on.' },
  { term: 'A*', section: 'games', text: 'The classic shortest-path search: grow outward from the start, always trying the cell that looks best (the cost so far plus a guess of the cost left, never an overestimate).' },
  { term: 'line of sight', section: 'games', text: 'Whether one point can see another: walk the cells (or cast a ray) between them and look for a wall.' },
  { term: 'vision cone', section: 'games', text: 'What a guard can see: within a distance, within an angle of where it faces, and not behind a wall.' },
  { term: 'boids', section: 'games', text: 'Reynolds\' flocking (1986): each agent steers by its neighbours alone (keep apart, line up, stay close) and a flock emerges.' },
  { term: 'steering', section: 'games', text: 'Moving an agent by forces toward a desired velocity (seek, flee, arrive, avoid) instead of setting its position: smooth, and they add up.' },
  { term: 'spatial hash', section: 'games', text: 'Space cut into a grid of buckets, each listing what is inside: finding neighbours means looking in a few nearby buckets, not checking everyone.' },
  { term: 'ring buffer', section: 'tools', text: 'A fixed-size list that wraps round: the newest entry overwrites the oldest, so it always holds the last N things (six seconds of history, the last 60 frame times).' },
  { term: 'serialisation', section: 'tools', text: 'Turning live objects into plain data (JSON) to save, send or load back: a level layout, a save game.' },
  { term: 'bullet pool', section: 'games', text: 'Thousands of projectiles kept as numbers in fixed arrays, reused instead of created and thrown away: no allocations, no garbage-collection hitches.' },
  { term: 'hitbox', section: 'games', text: 'The shape that counts for hits, often not the drawn one: shoot-\'em-ups make the hero\'s much smaller than its sprite, so near misses feel fair.' },
  { term: 'vehicle', section: 'physics', text: 'A car in games is usually one body (the chassis) on wheels that are rays: each finds the ground, pushes up like a spring and grips along and across.' },
  { term: 'suspension', section: 'physics', text: 'The springs and dampers between a car\'s body and its wheels: the body rolls in corners, pitches when braking and soaks up bumps.' },
  { term: 'determinism', section: 'physics', text: 'The same inputs giving exactly the same results every run: what replays, rollback netcode and seeded patterns rely on (physics is deterministic only with the same steps in the same order).' },
  // tools
  { term: 'agent API', section: 'tools', text: 'window.__WORLD__ and window.__PIXEL_ENGINE__: what tests and AI agents drive the game through.' },
  { term: 'e2e test', section: 'tools', text: 'A test that opens the real game in a browser, plays it and checks the frames and numbers.' },
];

const BY_TERM = new Map(GLOSSARY.map((t) => [t.term.toLowerCase(), t]));

export function term(word: string): Term | undefined {
  return BY_TERM.get(word.toLowerCase());
}
