/**
 * Clip Gallery: the hero's animations, eight at a time on mannequins. Pads switch the family
 * (moving, jumps and flips, ledges and climbing, fighting, weapons and spells, emotes);
 * labels name each clip.
 */
import type { RoomDef } from '../types';
import { HERO_CLIP_NAMES, type Mannequin, mannequin } from '../kit/mannequin';

const FAMILIES: { label: string; clips: string[]; note: string }[] = [
  { label: 'MOVING', clips: ['Idle', 'IdleLook', 'Tiptoe', 'Walk', 'Run', 'Skid', 'CrouchWalk', 'Crawl'], note: 'Locomotion: walk and run are generated by the gait tool from a few numbers (stride, lift, bounce); tiptoe, walk and run blend by speed in the game.' },
  { label: 'JUMPS', clips: ['Jump', 'DoubleJump', 'TripleJump', 'Backflip', 'SideFlip', 'LongJump', 'GroundPound', 'Dive'], note: 'Airborne clips: the game plays them over a physics arc; here they loop in place.' },
  { label: 'LEDGES', clips: ['Hang', 'ShimmyRight', 'PullUp', 'Climb', 'ClimbIdle', 'WallSlide', 'Teeter', 'Push'], note: 'Hands and feet that must meet the world: foot and hand goals are part of the clip data.' },
  { label: 'FIGHTING', clips: ['Punch', 'Punch2', 'Kick', 'SweepKick', 'JumpKick', 'HitReact', 'Roll', 'Death'], note: 'Every attack has an anticipation, a hit frame and a follow-through.' },
  { label: 'WEAPONS', clips: ['Slash1', 'Slash2', 'Slash3', 'Slam', 'Spin', 'Cast', 'CastBig', 'BowDraw'], note: 'Riftlight\'s combat clips on the same rig.' },
  { label: 'EMOTES', clips: ['Wave', 'Victory', 'Triumph', 'Shout', 'Sit', 'LieIdle', 'Sleep', 'Hurt'], note: 'Emotes and rests: the hero lies down by itself after 16 idle seconds.' },
];

export const CLIPS: RoomDef = {
  id: 'clips',
  title: 'Clip Gallery',
  wing: 'animation',
  about: 'The hero\'s animations, eight at a time on mannequins. Every clip is plain data (key poses and timing), compiled to three.js animation tracks against the rig and checked by numbers: feet on the floor, no sliding, smooth loops.',
  try: ['Walk the family pads from left to right', 'Slow everything down with T (clip speed) to see the poses hold', 'Stand next to Run and compare it with your own run: the game blends Walk and Run by speed'],
  spawn: [0, 0, 6],
  facing: Math.PI,
  background: 'navy',
  guide: {
    what: 'Eight mannequins (clones of the hero model) on plinths, each looping one clip, and six pads that switch to another family of clips. The label over each plinth is the clip name.',
    how: [
      'A clip is data in src/game/hero/clips/: keys at frames (30 a second), each a pose (joint rotations in degrees, a pelvis offset) with an easing, plus foot goals.',
      'compileClip turns the data into three.js quaternion tracks against the rig\'s rest pose, solving two-bone IK for the legs where a key gives a foot goal instead of angles.',
      'The clips address joints by name, so one compiled set plays on every clone of the model (these mannequins share it with the hero).',
      'npm run anim -- check measures every clip (feet through the floor, foot slide while planted, loop seams, joint limits) and fails CI on problems; sheet and curves draw contact sheets and motion curves as PNGs.',
      'In the game, PlatformerCharacter cross-fades clips without flipping joints (RotationBlend), blends Tiptoe, Walk and Run by speed, and places the feet on the real ground.',
    ],
    uses: ['Hand-keyed clips as data: the Animation Lab (lab.html) previews and scrubs them in the real renderer.', 'Procedural locomotion: Overgrowth and Rain World generate gaits; the walk and run here come from a gait generator.', 'Pose-to-pose animation: classic 2D sprite games hold key poses (try the steps eases).'],
    ask: ['a new emote clip for the hero as data', 'a walk cycle from stride, lift and bounce numbers', 'check every clip for foot sliding', 'a contact sheet of the run cycle'],
    cost: 'Per mannequin and frame: sampling a few dozen quaternion tracks and blending. Compiling all 90 clips takes a few milliseconds once per page.',
    code: [
      {
        title: 'A clip is data',
        file: 'src/game/hero/clips/emotes.ts',
        src: `name: 'Wave',
frames: 44,
grounded: true,
...track([
  [0, STAND_BODY, STAND_FEET],
  [7, waveUp(150, 40), STAND_FEET, 'out'],
  [12, waveUp(165, 20), STAND_FEET],
  ...
  [44, STAND_BODY, STAND_FEET],
]),`,
      },
      {
        title: 'Compiled once, shared by every clone',
        file: 'src/world/kit/mannequin.ts',
        src: `compiled ??= compileClips(HERO_CLIPS, HERO_RIG, m.scene);
...
const c = compiled!.find((x) => x.name === name);
...
const action = mixer.clipAction(c);`,
      },
    ],
    words: ['clip', 'rig', 'cross-fade', 'blend space', 'foot IK', 'contact sheet'],
  },
  async build(room) {
    const { kit, ctx } = room;
    kit.room(26, 18, { floor: ['navy', 'blue'] });
    let speed = 1;
    let family = 0;
    const spots = Array.from({ length: 8 }, (_, i) => ({ x: -10.5 + i * 3, z: -3 }));
    for (const s of spots) kit.cylinder([s.x, 0.2, s.z], 0.9, 0.4, 'slate', { segments: 12 });
    const known = new Set(HERO_CLIP_NAMES);
    const men: Mannequin[] = await Promise.all(spots.map((s, i) => mannequin(ctx, FAMILIES[0]!.clips[i]!, [s.x, 0.4, s.z], 0.35)));
    const labels = spots.map((s, i) => kit.label([s.x, 2.6, s.z], FAMILIES[0]!.clips[i]!, { color: 'sand', range: 14 }));
    const show = (f: number) => {
      family = f;
      FAMILIES[f]!.clips.forEach((name, i) => {
        const clip = known.has(name) ? name : 'Idle';
        men[i]!.play(clip);
        labels[i]!.text = clip.toUpperCase();
      });
    };
    FAMILIES.forEach((fam, i) =>
      kit.pad([-7.5 + i * 3, 0, 3.5], { label: fam.label, color: 'sky', group: 'family', initial: i === 0, note: fam.note, apply: () => show(i) }),
    );
    kit.light({ position: [0, 4, 0], color: 0xf4f4f4, intensity: 6, radius: 14 });
    return {
      knobs: [
        {
          id: 'speed',
          label: 'Clip speed',
          min: 0.05,
          max: 2,
          step: 0.05,
          initial: 1,
          get: () => speed,
          set: (v) => {
            speed = v;
            for (const m of men) m.mixer.timeScale = v;
          },
          format: (v) => `${v.toFixed(2)}x`,
        },
      ],
      update(dt) {
        for (const m of men) m.mixer.update(dt);
      },
      status: () => `${FAMILIES[family]!.label}: ${men.map((m) => m.clip).join(',')}`,
      api: { family: () => FAMILIES[family]!.label, clips: () => men.map((m) => m.clip), show },
    };
  },
};
